export default [
  "I made it to a phone screen for a technical writing internship in my freshman year of college. Try to top that, Stephen King.",
  "This website also serves as my Tinder account.",
  "Tip: To assert your dominance in an interview, ask the interviewer to solve a technical question. It'll change your chances of getting an offer from non-zero, to zero.",
  "Even my parents don't read this, why are you?",
  "How to use this website effectively: First, click the red dot in the top right/left corner of your browser. Then do something more productive.",
  "You reading this is why I coded this section!",
  "They same Rome wasn't built in a day. Neither was this website. A framework built this in a minute and I just Googled good-looking designs. It's called plagiarism, look it up.",
  "If you read any of my stories, you'll come to the conclusion that I don't have a ghost writer. Mostly because nothing I write is worthy of such outsourcing. But I probably am.",
  "I type so fast I write words that don't last.",
  "Why are you reading this?",
  "How many times have you reloaded this site to see if you've read all of these?",
  "Want to learn how to make a website like this? Don't!",
  'If this blog ever becomes technical or has posts about new technology and a "FULL TUTORIAL ON HTML," please let me know so I can shut this website down.',
  "Fun fact: This website was originally used in a school project. That's the highpoint of this website. It peaked early.",
  "My humor is so dry you need a bottle of water to digest it.",
]
